<?xml version="1.0"?>
<package format="2">
  <name>unified_launcher</name>
  <version>0.0.0</version>
  <description>The unified_launcher package</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>roslaunch</exec_depend>
  <exec_depend>unitree_legged_real</exec_depend>
  <exec_depend>mren_waste_collector</exec_depend>
  <exec_depend>open_manipulator_controller</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>open_manipulator_msgs</exec_depend>

</package>
