# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detection.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64\x65tection.proto\"t\n\x0bTrashObject\x12\r\n\x05x_pos\x18\x01 \x01(\x02\x12\r\n\x05y_pos\x18\x02 \x01(\x02\x12\x13\n\x0b\x64ist_meters\x18\x03 \x01(\x02\x12\x10\n\x08width_cm\x18\x04 \x01(\x02\x12\x11\n\tlenght_cm\x18\x05 \x01(\x02\x12\r\n\x05\x61ngle\x18\x06 \x01(\x02\"/\n\x0e\x44\x65tectionFrame\x12\x1d\n\x07objects\x18\x01 \x03(\x0b\x32\x0c.TrashObjectb\x06proto3')
)




_TRASHOBJECT = _descriptor.Descriptor(
  name='TrashObject',
  full_name='TrashObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_pos', full_name='TrashObject.x_pos', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_pos', full_name='TrashObject.y_pos', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_meters', full_name='TrashObject.dist_meters', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width_cm', full_name='TrashObject.width_cm', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lenght_cm', full_name='TrashObject.lenght_cm', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle', full_name='TrashObject.angle', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=135,
)


_DETECTIONFRAME = _descriptor.Descriptor(
  name='DetectionFrame',
  full_name='DetectionFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='DetectionFrame.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=184,
)

_DETECTIONFRAME.fields_by_name['objects'].message_type = _TRASHOBJECT
DESCRIPTOR.message_types_by_name['TrashObject'] = _TRASHOBJECT
DESCRIPTOR.message_types_by_name['DetectionFrame'] = _DETECTIONFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrashObject = _reflection.GeneratedProtocolMessageType('TrashObject', (_message.Message,), dict(
  DESCRIPTOR = _TRASHOBJECT,
  __module__ = 'detection_pb2'
  # @@protoc_insertion_point(class_scope:TrashObject)
  ))
_sym_db.RegisterMessage(TrashObject)

DetectionFrame = _reflection.GeneratedProtocolMessageType('DetectionFrame', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONFRAME,
  __module__ = 'detection_pb2'
  # @@protoc_insertion_point(class_scope:DetectionFrame)
  ))
_sym_db.RegisterMessage(DetectionFrame)


# @@protoc_insertion_point(module_scope)
