# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: states.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='states.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cstates.proto\"\x18\n\x06States\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\tb\x06proto3')
)




_STATES = _descriptor.Descriptor(
  name='States',
  full_name='States',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='States.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=40,
)

DESCRIPTOR.message_types_by_name['States'] = _STATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

States = _reflection.GeneratedProtocolMessageType('States', (_message.Message,), dict(
  DESCRIPTOR = _STATES,
  __module__ = 'states_pb2'
  # @@protoc_insertion_point(class_scope:States)
  ))
_sym_db.RegisterMessage(States)


# @@protoc_insertion_point(module_scope)
